### ISSUE TITLE
All User signup fails

### ISSUE THREAD

**Issue by tobyk100** [tobyk100/403-kamal#13]
When a user trys to sign up, error occurs. There is some sort of duplicate user error.

**Comment by ktang92** [comment]
We previously had 17 or 18 users in the database. A change that we made reset the numbering, which made it error out when we tried to add new users because users with the id we were going to assign already existed. Failing enough times allowed the user id to increment enough to resync with the database.

**Comment by acetang** [comment]
Closing it until it repro.
